gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"

customCommands:
  - key: "<c-a>"
    command: "nvim -c 'lua require(\"CopilotChat\").ask(\"Generate a concise and descriptive commit message (no quotes) for the following changes:\", { selection = vim.fn.system(\"git diff --cached\") })' -c 'normal ggVGy' -c 'wq' {{filename}}"
    context: "commits"
    description: "Generate commit with CopilotChat"
    loadingText: "Asking Copilot for a commit message..."
    subprocess: true
